# Generated by Django 4.0.4 on 2022-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('health', models.IntegerField(default=None, null=True)),
                ('experience', models.IntegerField(default=None, null=True)),
                ('speed', models.IntegerField(default=None, null=True)),
                ('armor', models.IntegerField(default=None, null=True)),
                ('maxdmg', models.IntegerField(default=None, null=True)),
                ('summon', models.CharField(default=None, max_length=50, null=True)),
                ('convince', models.CharField(default=None, max_length=50, null=True)),
                ('illusionable', models.CharField(default=None, max_length=20, null=True)),
                ('pushable', models.CharField(default=None, max_length=50, null=True)),
                ('pushes', models.CharField(default=None, max_length=50, null=True)),
                ('killstounlock', models.IntegerField(default=None, null=True)),
                ('senseinvis', models.CharField(default=None, max_length=50, null=True)),
                ('dmgfromphysical', models.IntegerField(default=None, null=True)),
                ('dmgfromdeath', models.IntegerField(default=None, null=True)),
                ('dmgfromholy', models.IntegerField(default=None, null=True)),
                ('dmgfromice', models.IntegerField(default=None, null=True)),
                ('dmgfromfire', models.IntegerField(default=None, null=True)),
                ('dmgfromenergy', models.IntegerField(default=None, null=True)),
                ('dmgfromearth', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
