# Generated by Django 4.0.4 on 2022-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibiahelper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='listofloot',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='illusionable',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
