# Generated by Django 4.0.4 on 2022-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibiahelper', '0002_creature_listofloot_alter_creature_illusionable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='experience',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
